from .settings import group_names

d = {}
d[group_names[0]] = [
    "notable",
    "sun-awt-X11-XFramePeer",
    "MATLAB R2019b - academic use",
    "terminator",
    "atom",
    "geany",
    "brackets",
    "code-oss",
    "code",
    "thunar",
    "nemo",
    "caja",
    "nautilus",
    "org.gnome.nautilus",
    "pcmanfm",
    "pcmanfm-qt",
    "Atom",
    "Alacritty",
    "Sublime_text",
    "sublime_text",
    "Geany",
    "Brackets",
    "Code-oss",
    "Code",
    "Thunar",
    "Nemo",
    "Caja",
    "Nautilus",
    "org.gnome.Nautilus",
    "Pcmanfm",
    "Pcmanfm-qt",
    "evince",
]
d[group_names[1]] = [
    "brave-browser",
    "Brave-browser",
    "Firefox",
    "firefox",
    "Navigator",
    "Chromium",
    "chromium",
    "google-chrome-beta",
    "Google-chrome-beta",
    "qbittorrent",
    "transmission-qt",
    "transmission-gtk",
]
d[group_names[2]] = [
    "ferdium",
    "discord",
    "telegramDesktop",
    "whatsapp-for-linux",
]
d[group_names[3]] = ["virt-manager", "gimp-2.10", "Gimp-2.10"]
d[group_names[4]] = [
    "balena-etcher-electron",
    "gnome-control-center",
    "blueman-manager",
    "nitrogen",
    "pling-store",
    "Xfce4-power-manager-settings",
    "pavucontrol",
    "lxappearance",
    "lightdm-settings",
]
d[group_names[5]] = [
    "gl",
    "anbox",
    "www.youtube.com",
    "www.youtube.com__watch",
    "crx_agimnkijcaahngcdmfeangaknmldooml",
    "Spotify",
    "Pragha",
    "Clementine",
    "Deadbeef",
    "Audacious",
    "spotify",
    "pragha",
    "clementine",
    "deadbeef",
    "audacious",
    "anbox",
    "Vlc",
    "vlc",
    "Mpv",
    "mpv",
    "obs",
]
