#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xsetroot -solid "#1e1e2e"
xsetroot -cursor_name left_ptr
exec vncviewer
# exec openbox
# /home/ervin/.local/bin/autostart &
# exec alacritty -o "window.dimensions.columns: 52" -o "window.dimensions.lines: 30" -o "window.position.x: 684" -o "window.position.y: 0" & zathura
# exec zathura
# exec alacritty
# exec start-newm -d 
# exec dwm
# exec qtile start
